server:
  port: 8083
spring:
  application:
    name: zlyy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3336/zlyy?useSSL=false&serverTimezone=UTC
    username: root
    password: zlyy-biubiubiuer
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  type-aliases-package: com.example.zlyy.entity
  global-config:
    db-config:
      table-prefix: tb_
logging:
  level:
    com.example.zlyy: debug
  pattern:
    dateformat: mm:ss.SSS
    
    
    
