---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by biubiubiuer.
--- DateTime: 2022/10/13 16:26
---

-- 1. 参数列表
-- 1.1 openId
local openId = ARGV[1]
-- 1.2 biochemicalIndicatorsStr
local biochemicalIndicatorsStr = ARGV[2]

-- 2. 数据 key
-- 2.1 openId + indi_infix
local indiKey = "openid:" .. openId .. ":indi_infix:"

-- 3. 脚本业务
-- 3.1 判断 redis 里是否存在键: "indiKey"
local is_exists = redis.call("EXISTS", indiKey)

if is_exists == 1 then
    redis.call("DEL", indiKey)
    -- 3.2 存在, 则更新生化指标结果字符串
    redis.call("SET", indiKey, biochemicalIndicatorsStr)
    return 2
else
    redis.call("SET", indiKey, biochemicalIndicatorsStr)
    return 1
end