---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by biubiubiuer.
--- DateTime: 2022/10/13 16:43
---

-- 1. 参数列表
-- 1.1 openId
local openId = ARGV[1]
-- 1.2 questionnaireStr
local questionnaireStr = ARGV[2]

-- 2. 数据 key
-- 2.1 openId + ques_infix
local quesKey = "openid:" .. openId .. ":ques_infix:"

-- 3. 脚本业务
-- 3.1 判断 redis 里是否存在键: "quesKey"
local is_exists = redis.call("EXISTS", quesKey)

if is_exists == 1 then
    redis.call("DEL", quesKey)
    -- 3.2 存在, 则更新调查问卷结果字符串
    redis.call("SET", quesKey, questionnaireStr)
    return 2
else
    redis.call("SET", quesKey, questionnaireStr)
    return 1
end